### ISSUE TITLE
code for G2 or BCP3?

### ISSUE THREAD

**Issue by petep0p** [inarighas/BionxConsole#3]
hello! I'm trying to use a bionx battery on a non-bionx system, and am trying to adapt your work to different hardware to get that done.

can you tell me if your code was written for the G2 can system, or was it for the newer "BCP3" can system?

the packet IDs I'm seeing don't seem to correspond to what you have.

anyway, thanks for sharing your work!

**Comment by inarighas** [comment]
I cannot tell your exactly to which version it correpsonds. It would probably be the old system. 
This was tested with one electrical bike old model "Matra iStep One 28inch". It is a 2008 bike  that uses a Bionx 700 engine. However, Electric bikes protocol have changed a lot since then I guess 😆 .

You can find in this link the product specification https://www.caradisiac.com/Un-nouveau-velo-a-assistance-electrique-le-Matra-i-step-ONE-4778.htm (but it is in French)

**Comment by petep0p** [comment]
that you very much. that clears it up. it's a G2 system. i guess they changed the CAN protocol quite a lot, but i think i can still get some use from the work you did.

much appreciated!
